export type Evidence = '기초 이론' | '물리 근사' | '관측 기반' | '반드시 가설' | '표시·수치 기법';
export interface KnowledgeItem { terms: string; category: string; evidence: Evidence; explanation: string; limits: string; sources?: string[] }
export const REFERENCES: Record<string,{ title:string; url:string; use:string }> = {
  cloudHeight:{title:'US National Weather Service — Cloud classification',url:'https://www.weather.gov/lmk/cloud_classification',use:'고층·중층 구름 분류. 고정 12 km 전 지구 층은 모델 배치 가정이다.'},
  nasaMoon:{title:'NASA — Solar Wind on the Moon',url:'https://science.nasa.gov/moon/solar-wind/',use:'달의 전역 자기장 부재·국소 지각 자기장. 달을 강한 전역 자석으로 설정하는 근거가 아님.'},
  monopole:{title:'CERN — MoEDAL zeroes in on magnetic monopoles (2024)',url:'https://home.cern/moedal-zeroes-magnetic-monopoles/',use:'자기 단극자 탐색의 미검출 결과. 단극자 존재 확인과 구분.'},
  shue:{title:'Shue et al. (1998), Magnetopause location under extreme solar wind conditions',url:'https://doi.org/10.1029/98JA01103',use:'태양풍 동압·IMF Bz에 따른 자기권계면 경험식. 임의 외부 자기원이나 무한장 MHD 해가 아님.'},
  core:{title:'Livermore et al. (2017), An accelerating high-latitude jet in Earth’s core',url:'https://doi.org/10.1038/ngeo2859',use:'자기장으로 추정한 국소 외핵 제트 속도. 외핵 전체의 고정된 속도나 외부장 응답 임계값이 아님.'},
  dynamo:{title:'Landeau et al. (2022), Sustaining Earth’s magnetic dynamo',url:'https://doi.org/10.1038/s43017-022-00264-1',use:'지구 다이너모 에너지·대류 기작의 리뷰. 이 앱의 외핵 결합계수를 입증하지 않음.'},
  mhd:{title:'Deguen & Lasbleis (2019), Fluid dynamics of Earth’s core',url:'https://arxiv.org/abs/1905.10416',use:'자기유체역학·유도 방정식의 배경. 앱은 전체 3D MHD를 풀지 않음.'},
  ocean:{title:'ESA — Swarm detects tidal signatures of our oceans (2025)',url:'https://www.esa.int/Applications/Observing_the_Earth/FutureEO/Swarm/Swarm_detects_tidal_signatures_of_our_oceans',use:'해양 조석의 약한 자기 신호 관측. 달 전역 쌍극자와 다른 기작이며 현재 앱에는 포함되지 않음.'},
  cern:{title:'CERN — CLOUD experiment overview',url:'https://home.cern/science/experiments/CLOUD/',use:'대기 에어로졸 핵생성·성장 실험의 배경. 지진운·지진 예측을 증명한 실험이 아님.'},
  dunne:{title:'Dunne et al. (2016), Global atmospheric particle formation from CERN CLOUD measurements',url:'https://doi.org/10.1126/science.aaf2649',use:'황산·암모니아 등 핵생성 의존성. 앱의 모든 계수를 논문에서 적합한 것은 아님.'},
  almeida:{title:'Almeida et al. (2013), Molecular understanding of sulphuric acid–amine particle nucleation',url:'https://doi.org/10.1038/nature12663',use:'황산–디메틸아민 핵생성 채널의 근거.'},
  he:{title:'He et al. (2023), Iodine oxoacids enhance nucleation of sulfuric acid particles in the atmosphere',url:'https://doi.org/10.1126/science.adh2526',use:'요오드 산화산과 황산의 핵생성 결합. 지자기 결합식의 근거가 아님.'},
  shen:{title:'Shen et al. (2024), New particle formation from isoprene under upper-tropospheric conditions',url:'https://doi.org/10.1038/s41586-024-08196-0',use:'저온 상부대류권 이소프렌 유래 산화물 핵생성 적용 환경.'},
  msa:{title:'Baalbaki et al. (2026), Role of methanesulfonic acid in atmospheric particle nucleation and growth',url:'https://doi.org/10.1038/s41586-026-10810-2',use:'기존 프로그램의 MSA 채널 참고문헌. 앱의 성장률·핵생성 수치는 스크리닝 가정값.'},
  kohler:{title:'Petters & Kreidenweis (2007), A single parameter representation of hygroscopic growth and cloud condensation nucleus activity',url:'https://doi.org/10.5194/acp-7-1961-2007',use:'κ-Köhler 임계 건조직경 계산. 실제 구름량으로 직접 변환되지 않음.'},
  tide:{title:'Métivier et al. (2009), Evidence of earthquake triggering by the solid earth tides',url:'https://doi.org/10.1016/j.epsl.2008.12.024',use:'고체 지구 조석 섭동의 규모 참고. 앱의 단층별 파열이나 지진 시점을 검증하지 않음.'},
  mw:{title:'Kanamori (1977), The energy release in great earthquakes',url:'https://doi.org/10.1029/JB082i020p02981',use:'지진모멘트와 모멘트 규모의 배경. 합성 입력으로 얻은 Mw는 관측 규모가 아님.'},
  droplet:{title:'Guo & Xue (2021), The enhancement of droplet collision by electric charges and atmospheric electric fields',url:'https://doi.org/10.5194/acp-21-69-2021',use:'하전 물방울과 전기장 효과. 자기장만으로 지진운이 만들어진다는 근거가 아님.'},
  magnetophoresis:{title:'Suwa et al. (2023), Applications of magnetic and electromagnetic forces in micro-analytical systems',url:'https://doi.org/10.1039/D2LC00702A',use:'자기력·입자 힘과 유체 항력 배경. 대기 물방울의 강한 자기 정렬을 보장하지 않음.'},
};

// Entries group aliases used in controls, formulas, legends and exported diagnostics.
const item=(terms:string,category:string,evidence:Evidence,explanation:string,limits:string,sources?:string[]):KnowledgeItem=>({terms,category,evidence,explanation,limits,sources});
export const KNOWLEDGE: KnowledgeItem[] = [
  item('구름층 고도 · 대류권계면 · 권적운 · 고적운 · 양떼구름','대기','물리 근사','기본 중심 12 km, 반두께 1.5 km의 지정 층. 대류권계면 높이는 위도·계절에 따라 다르다. 고층의 작은 양떼 모양인 권적운은 중층의 고적운과 구분한다.','입자를 제한하는 경계조건이지 자발적 구름 생성 해가 아니다. 고도 ×30/×100은 표시 전용이다.',['cloudHeight']),
  item('쌍극자 자체 회전 · 공전 · °/화면 초','자기장','표시·수치 기법','자체 회전은 N/S 축 각도, 공전은 위치를 바꾼다. 음수 속도는 반대 방향, 일시정지는 둘 다 멈춘다.','지정 운동이지 토크·관성 모멘트를 적분한 자유 강체 운동은 아니다.'),
  item('자기장 B · 자속밀도 · nT · μT · T · B*','단위','기초 이론','테슬라 T는 자기장 단위. 1 nT=10⁻⁹ T, 1 μT=1,000 nT. B*=B/(31,200 nT)는 내부 정규화 값이다.','색상 밝기나 선 개수는 측정값이 아니다.'),
  item('거리 r · R_E · km · 고도 · X Y Z · 좌표','단위','표시·수치 기법','1 R_E=6,371 km. 거리 r은 지구 중심으로부터 √((x−xE)²+(y−yE)²+z²). 지표 고도는 r−1 R_E. 2D는 3D의 z=0 단면이다.','구름은 지정 물리 고도층에 배치한다. 고도 표시 배율은 표시 전용이며 대기 광륜 역시 설명용이다.'),
  item('쌍극자 dipole · m · M_E · N극 S극 · r⁻³','자기장','물리 근사','쌍극자 자기장은 멀리서 거리 세제곱에 반비례하며 방향에도 의존한다. M_E는 앱의 지구 기준 모멘트 배율. N/S는 한 쌍의 자극이다.','모든 자기장이 하나의 순수 쌍극자는 아니다. 다극 성분·전류·공간 경계 조건이 가능하다.'),
  item('단극자 monopole_n monopole_s · q_m · 자기 전하','자기장','반드시 가설','N 또는 S만 있는 독립 자기원을 합성한 실험이다. 보통 자석을 자르면 N/S 쌍이 다시 생긴다.','독립 자기 단극자는 발견이 확립되지 않았다. N/S 프리셋을 실제 천체로 해석하지 않는다.',['monopole']),
  item('균일장 · uniform · 먼 외부 자기원','자기장','물리 근사','작은 영역에서 거의 일정한 외부장을 근사한다. 방향은 +Y축으로부터 회전각으로 정한다.','국소 근사일 뿐 우주 전역에 무한히 일정한 실제 자기원이 아니다.'),
  item('외부 자기원 기준 nT · strength · 자극 세기','자기장','물리 근사','쌍극자 입력은 자기원 중심에서 1 R_E 떨어진 적도의 이상적 세기. 단극자는 1 R_E 방사 세기. 구버전 strength=1은 31,200 nT 기준으로 호환한다.','지구에 도달한 세기와 자기원 기준 세기는 다르다. 지구 중심 외부장 읽기 값을 비교한다.'),
  item('∞ · 무한대 · 과학적 표기 · 1e1000 · 상한 limit','수치','표시·수치 기법','nT 입력에 임의의 물리 상한을 두지 않는다. 로그 크기와 단위 벡터로 초대형 값을 합성한다. ∞는 유한한 장보다 우세한 방향을 나타내는 극한 모드다.','지수는 컴퓨터가 정확히 표현하는 정수 범위여야 한다. 상쇄하는 무한장·상대 증가율 미지정은 미정이며 무한 에너지의 실제 반응을 예측하지 않는다.'),
  item('중첩 · superposition · B_total · B_E · B_ext','자기장','물리 근사','합성 벡터 B_total=B_E+B_ext. 자기원은 성분별로 더하며 표시 배율을 수식에 곱하지 않는다.','플라스마 전류가 만드는 자기권 피드백·차폐·재결합 동역학은 풀지 않은 정자기 근사다.'),
  item('경사각 tilt θ · 극성 반전 reversal · 마투야마–브륀스','자기장','물리 근사','자기 모멘트 축의 회전 및 방향 뒤집기. 실제 역전은 복잡한 장기 변화이다.','버튼으로 즉시 뒤집는 모습은 시간발전 역전 모델이 아니다. 지리적 북쪽과 자석 N 표기를 혼동하지 않는다.'),
  item('자기력 · Lorentz 로런츠 · J×B · q(E+v×B)','이론','기초 이론','전하의 힘은 q(E+v×B), 전도 유체의 자기 체적력은 J×B이다. 장 B 자체와 힘 F는 다른 물리량이다.','자기장 방향으로 입자를 움직이는 것만으로 Lorentz 힘 계산이 되지 않는다.',['mhd','droplet']),
  item('μ₀ · 진공 투자율 · 자기압 P_mag · nPa Pa kPa MPa','단위','기초 이론','P_mag=B²/(2μ₀), μ₀≈4π×10⁻⁷ H/m. 압력 1 Pa=10⁹ nPa, 1 kPa=10³ Pa, 1 MPa=10⁶ Pa.','자기 에너지 밀도/압력이 곧바로 같은 크기의 지각 응력을 발생시킨다는 뜻은 아니다.'),
  item('구배 gradient ∇|B| ∇B² · 공간 변화','자기장','기초 이론','위치에 따른 자기장 세기 변화율. 실제 단위는 nT/km 등이며 내부 미분은 B*/R_E로 계산한다.','벡터 외적과 구배는 차원이 달라 정규화 없이 더할 수 없다.'),
  item('자기권 magnetosphere · 자기권계면 magnetopause · 약자기장 등치선','자기장','물리 근사','보라 점선은 사용자가 정한 |B_E| 기준의 이상적 쌍극자 등치선. 주황 선은 태양풍에 따른 Shue 자기권계면이다.','자기장이 0이 되는 절대 경계가 아니다. 두 선은 의미가 다르며 외부장 때문에 생긴 국소 영점도 경계면 전체가 아니다.',['shue']),
  item('Shue · r₀ · alpha α · 태양 천정각 θ · dayside magnetotail','이론','물리 근사','r(θ)=r₀[2/(1+cosθ)]^α. r₀와 α는 태양풍 동압 및 IMF Bz 함수. 이 앱의 태양 방향은 −X이다.','앱 보호 범위 P=0.05–100 nPa, |Bz|≤50 nT 밖에서는 선을 숨기고 경고한다. 이는 논문의 보편적 유효 범위를 선언한 것이 아니다. 임의 외부장을 포함한 경계는 미해결.',['shue']),
  item('태양풍 solar wind · 플라스마 · 동압 P_dyn · ρv²','우주환경','물리 근사','전하를 가진 입자 흐름. 양성자 근사 동압[nPa]=1.6726×10⁻⁶ n[cm⁻³] v[km/s]².','밀도·속도·자기장 방향·시간이 함께 중요하다. 외부 자기장 하나의 nT 임계값만으로 모든 영향을 결정할 수 없다.'),
  item('IMF · Bx · Bz · 남향 북향 · CME · 지자기 폭풍','우주환경','기초 이론','IMF는 행성간 자기장. 남향 Bz는 자기권 결합에 중요하며 CME는 코로나 질량 방출이다. UI의 Y축에 IMF Bz를 대응한다.','CME 버튼은 가상 조건 변화이며 실제 태양 관측 사건 재현은 아니다.'),
  item('Bow shock 활모양 충격파 · 재결합 reconnection · X-point 중성점','우주환경','물리 근사','태양풍 충격파와 자기권계면은 서로 다른 면이다. 자기장 영점은 재결합 후보 구조와 관련될 수 있다.','정자기 영점 탐지만으로 재결합률·입자 가열·에너지 유입을 계산한 것이 아니다. 이전 고정 원뿔 Bow Shock 표시는 제거했다.'),
  item('밴앨런대 · 방사선대 · 오로라 · 전리층 열권 중간권','우주환경','기초 이론','자기권 입자 포획 영역, 극지 발광 현상, 전리된 대기와 고도별 대기층을 뜻한다.','앱의 광륜·입자·펄스는 해당 현상을 정량적으로 해석한 결과가 아니다.'),
  item('달 공전 · 자전 · 위상 phase · 삭 망 상현 하현 · 동주기','달','관측 기반','대표 거리 60.3 R_E, 항성 공전 주기 27.32일. 자전 방향 표시를 공전 위상에 동기화한다. 실제 일/화면 초 배율이 2D·3D에 공통 적용된다.','원궤도·일정 주기 근사이며 이심률·경사·삭망월과 항성월 차이를 정밀 계산하지 않는다.',['nasaMoon']),
  item('달 잔류자기 · remanentMoment · 국소 지각 자기장 · 나침반','달','관측 기반','달에는 지구 같은 확인된 전역 자기장이 없고 국소 자기 이상이 있다. 지구 나침반처럼 일관된 자기 북쪽을 기대할 수 없다.','국소 달 자기장 지도는 현재 불러오지 않는다. 전역 쌍극자 기본 OFF는 국소장이 없다는 뜻이 아니다.',['nasaMoon']),
  item('달 전역 쌍극자 · hypothesisDipoleEnabled · m_M','달','반드시 가설','이전 전역 달 쌍극자는 선택적인 가설 모드로 분리했다. 실제 거리와 동주기 방향을 사용한다.','관측된 달의 전역 자기 모멘트가 아니며 기본값은 OFF/0.',['nasaMoon']),
  item('조석 tide · tidalStressWeight · 기조력 · tidal bulge','달','물리 근사','가역적 사중극 형태 응력∝d⁻³ cos(2Δθ), 대표 최대 4 kPa로 보정한다.','조석 섭동을 판구조 하중처럼 계속 누적하지 않는다. 과장된 지구 팽창 그림은 기본 OFF. 해양·전리층 자기 조석은 미계산.',['tide','ocean']),
  item('달 플라스마 wake 공동 · wakeCavityStrength','달','물리 근사','달 뒤쪽의 플라스마 변화는 실제 연구 대상이지만 기존 단위 혼합 wake 식은 삭제했다.','legacy 필드는 호환용일 뿐 계산에 적용되지 않는다. 완전한 플라스마 모델이 필요하다.',['nasaMoon']),
  item('외핵 · 내핵 · 맨틀 · 철 합금 · Mg 규산염 · 다이너모','외핵','기초 이론','전도성 액체 철 합금 외핵의 유동·회전·열/조성 대류가 지구 자기장 생성과 연관된다. 마그네슘 규산염 맨틀과 구분한다.','지구를 막대자석으로 그리는 것은 외부장 근사이며 내부 원인이 영구자석이라는 뜻이 아니다.',['dynamo','mhd']),
  item('외핵 유속 · km/년 · mm/s · 고위도 제트','외핵','관측 기반','대표 유동 규모 10–20 km/년, 기본 모델값 15 km/년≈0.475 mm/s. 문헌의 국소 제트는 약 40 km/년으로 추정되기도 했다.','직접 측정한 외핵 전체 고정 속도가 아니다. 화면 순환은 가시성을 위해 재척도한 설명도.',['core']),
  item('자기유체역학 MHD · 유도 방정식 · η · Coriolis 코리올리','이론','기초 이론','∂B/∂t=∇×(u×B)+η∇²B와 운동 방정식을 함께 풀어 전도 유체와 자기장을 해석한다.','앱은 완전한 지구 다이너모·3D MHD 솔버가 아니다.',['mhd']),
  item('외부장–외핵 결합 · Δu · κ · 전달률 T · 응답시간 τ','외핵','반드시 가설','정상상태 민감도 Δu=κ T² P_ext τ/(ρL). ρ=11,000 kg/m³, L=2,260 km는 대표 가정. κ 부호가 가속/감속 방향을 지정한다.','관측으로 입증된 응답 법칙이나 임계값이 아니다. T=0, κ=0, OFF에서 Δu=0. 지구 모멘트로 자동 피드백하지 않는다.'),
  item('혜성 comet · 코마 coma · 승화 · gasActivity · 이온 꼬리','외부 자극','반드시 가설','혜성 가스/플라스마 효과를 활동도·꼬리 길이로 표현하는 기존 합성 프록시이다.','실제 혜성이 강한 자기 단극자라는 뜻이 아니며 화학·이온화·MHD를 풀지 않는다. 활동도는 nT가 아니다.'),
  item('지진운 earthquake cloud · wave cloud · 결맞음 밴드','가설','반드시 가설','외부 자기장과 대기 입자 패턴 사이의 제안된 결합을 시각화한다. 대조군은 같은 기상 조건에서 해당 결합을 끈 상태다.','구름 모양만으로 지진을 예측하거나 가설이 증명되었다고 판단할 수 없다.'),
  item('A_h · hypothesisCoupling · hypothesisEnabled · null control 대조군','가설','반드시 가설','A_h는 자기–대기 결합의 무차원 가정 계수. OFF 또는 A_h=0이면 가설 증분이 정확히 0이다.','관측 데이터로 추정된 보편 상수가 아니다. 동일 조건의 coupled−control을 비교한다.'),
  item('간섭 I · shear 전단각 · external_ratio · gradientWeight α','가설','반드시 가설','s=|B_E×B_X|/(|B_E||B_X|), q=|B_X|/(|B_E|+|B_X|), g=tanh(L|∇B|/B), I=q[(1−α)s+αg].','0–1 무차원 진단 점수이며 실제 간섭 에너지나 지진 확률이 아니다.'),
  item('hotspot mask · sigmoid · I_th · steepness k · externalStimulusThreshold','가설','반드시 가설','시그모이드로 진단 점수를 부드럽게 활성화한다. 임계값과 경사도는 가설 패턴을 고르는 조절값이다.','nT 단위의 실제 지구 반응 임계값이 아니다.'),
  item('파장 λ · waveWavelength · k_perp · 위상 Φ · 직교 파동','가설','반드시 가설','자기장에 수직인 방향의 코사인 패턴으로 가상 구름 띠를 만든다. 파장은 모델 좌표 R_E 스케일이다.','대기 중 관측된 실제 파동 분산관계나 지진운 간격을 계산한 것이 아니다.'),
  item('에어로졸 · 하전 물방울 · chargeRatio · polarizationSusceptibility χ','대기','물리 근사','공기 중 입자·전하 분율·유효 자기 감수성 민감도 변수이다. 물방울에 대한 실제 전자기 효과는 크기·전기장·유체 영향을 함께 요구한다.','입자가 자력선에 강하게 정렬되는 화면은 측정된 대기 운동이 아니다.',['droplet','magnetophoresis']),
  item('Stokes 스토크스 항력 · viscosity η · 자기영동 · Langevin · 난류 확산 D_t','대기','물리 근사','작은 입자의 점성 항력과 확률 확산을 사용한다. 자기영동 근사 F=VΔχ∇B²/(2μ₀).','점성·확산 및 일부 속도는 설명용 모델 단위. 일반 물방울의 지자기 효과는 매우 작을 수 있다.',['magnetophoresis']),
  item('particleCount · size · opacity · life · alignment · condensationThreshold','표시','표시·수치 기법','입자 수·표시 크기·투명도·수명·정렬도·응결 표시 문턱을 제어한다.','실제 분자 개수·물방울 크기 분포·강수량으로 해석하지 않는다.'),
  item('CERN CLOUD · 핵생성 nucleation J* · 이온 유도','에어로졸','물리 근사','대기 전구물질이 작은 입자를 생성하는 과정. J* 단위는 cm⁻³ s⁻¹. 앱은 논문의 경향을 참고한 스크리닝 계산이다.','CLOUD 실험 전체를 재현한 적합식이 아니며 자기장–지진 인과의 증거가 아니다.',['cern','dunne']),
  item('황산 H₂SO₄ SA · 암모니아 NH₃ · DMA 디메틸아민','에어로졸','물리 근사','황산–염기 계열 핵생성 채널. 앱은 황산 농도의 세제곱·암모니아 의존성과 DMA 채널을 사용한다.','대표 스크리닝 계수이며 모든 조건에 적용되는 측정식이 아니다.',['dunne','almeida']),
  item('HIOx · 요오드 산화산 · iodineOxoacid · 해양 극지','에어로졸','물리 근사','차가운 해양/극지 환경의 요오드 산화산 채널이다.','프리셋은 적용 환경 선택이지 해당 지역의 실시간 관측값이 아니다.',['he']),
  item('IP-OOM · 이소프렌 산화물 · 상부대류권','에어로졸','물리 근사','저온 상부대류권에서 이소프렌 유래 산화 유기물이 입자 형성에 기여할 수 있다.','지상 모든 환경으로 그대로 확대 적용할 수 없다.',['shen']),
  item('MSA · 메테인설폰산 · methanesulfonic acid','에어로졸','물리 근사','해양 황 계열 전구물질의 핵생성/성장 관련 스크리닝 채널.','앱 계수는 논문 전체 반응기작의 정밀 재현이 아니다.',['msa']),
  item('이온쌍 생성률 q · ionPairProduction · cm⁻³ s⁻¹','단위','물리 근사','단위 부피·초당 생성되는 이온쌍 수. 이온 유도 핵생성분은 q 이하로 제한한다.','자기장이 강하면 이온이 무한히 생긴다는 모델이 아니다.',['cern']),
  item('농도 cm⁻³ · pptv · mol · nm · nm/h','단위','기초 이론','cm⁻³은 세제곱센티미터당 개수, pptv는 10⁻¹² 부피 혼합비, nm는 10⁻⁹ m, nm/h는 입자 직경 성장 속도이다.','농도와 혼합비는 온도·압력 정보 없이 동일한 숫자로 바꿀 수 없다.'),
  item('응축손실 CS · condensationSink · 노출시간 · 생존율','에어로졸','물리 근사','증기 생존율 exp(−CS·t), CS 단위 s⁻¹, t 단위 초.','단일 지수 손실은 복잡한 대기 수송·화학의 축약이다.'),
  item('성장률 GR* · growthHours · D_final · 최종 건조직경','에어로졸','물리 근사','D_final=1.7 nm+GR*·t. 기존 스크리닝의 성장률 범위는 0–60 nm/h이다.','이 범위는 에어로졸 모델 가정이며 외부 자기장 nT 상한과 무관하다.'),
  item('CCN · 구름응결핵 · 과포화도 s_c · 흡습성 κ · Köhler 쾰러','에어로졸','물리 근사','κ-Köhler 이론으로 임계 건조직경을 구해 CCN 활성 가능성을 비교한다.','0–1 출력은 비교 점수이며 CCN 개수 농도나 실제 구름량/예보가 아니다.',['kohler']),
  item('기상 기준선 연결 · coupleToCloudBaseline · aerosolExperiment','에어로졸','반드시 가설','켜면 CLOUD 스크리닝 점수로 기존 기상 구름 프록시를 70–100% 범위에서 조정한다. 기본은 독립 실험이다.','관측으로 검증된 구름량 전환식이 아니며 A_h와 별개이다.'),
  item('온도 K °C · 기압 hPa · 상대습도 RH % · 이슬점','단위','기초 이론','K=°C+273.15. 1 hPa=100 Pa. 상대습도는 해당 온도의 포화 수증기압 대비 비율이며 이슬점은 응결이 시작되는 온도이다.','서로 다른 고도·환경의 값을 혼합하면 해석이 달라진다.'),
  item('풍속 m/s km/s · U V · 풍향 degree · 운량 %','기상','관측 기반','대기 U/V는 바람 성분, 풍향은 방위각, 운량은 하늘을 덮는 비율이다. 태양풍 속도 km/s와 대기 풍속 m/s를 구분한다.','기상 구름 프록시는 실제 구름 사진/위성 복원 모델이 아니다.'),
  item('NOAA GFS · ECMWF IFS · DWD ICON · Open-Meteo · SWPC','기상','관측 기반','기상/우주환경 자료 제공 체계 또는 수치예보 모델명. 앱에서 실제로 성공한 자료만 live로 표시한다.','프리셋 이름만으로 그 기관의 실시간 모델을 실행한 것이 아니다. 실패·일부 수신·manual 상태를 확인한다.'),
  item('Kp · Dst · 지자기 지수 · lastUpdated · live partial preset manual','기상','관측 기반','Kp는 행성 규모 교란 지수, Dst는 nT 단위의 적도권 교란 지수. live/partial은 수신 상태, preset/manual은 가정 입력이다.','지수 하나가 지역 자기장이나 지진 발생 확률을 직접 나타내지 않는다.'),
  item('단층 노드 · accumulatedStress · tectonicLoadingRate · failureIndex','지각','반드시 가설','단층을 이산 노드로 나타내며 판구조 하중과 가역적 섭동으로 합성 실패지수를 계산한다.','실제 단층 형상·마찰·응력 관측을 역산한 지진 예측기가 아니다.'),
  item('Coulomb 쿨롱 · σ_crit · 응력강하 Δσ · K_h · 자기–지각 결합','지각','반드시 가설','마찰 파괴 개념을 참고한 문턱과 가역적 자기 결합 Δσ_h=K_h |B_X|/(|B_E|+|B_X|)을 사용한다.','K_h는 가설 계수다. 자기장이 실제 단층 응력을 이 식대로 바꾼다는 검증이 없다.'),
  item('가상 파열 · seismicMoment M₀ · N·m · Mw · Richter 리히터','지각','물리 근사','가정한 원형 균열 반경 a와 응력강하로 M₀=(16/7)Δσa³, Mw=(2/3)(log₁₀M₀−9.1)를 계산한다.','Mw는 리히터 국지 규모와 다르다. 가상 파열 결과를 관측 지진 규모로 해석하지 않는다.',['mw']),
  item('P파 · S파 · 진원 깊이 depthKm · 파면','지각','표시·수치 기법','P는 종파, S는 횡파. 화면의 확장 원은 가상 사건 위치와 시간 경과를 표현한다.','지층별 실제 탄성파 전파·진동 세기·도달 시간 예보가 아니다.'),
  item('RK4 · Runge–Kutta · streamline 자기력선 · flux tube','수치','표시·수치 기법','dr/ds=B/|B|를 4차 수치 적분한다. 2D는 같은 3D 벡터장의 평면 투영 방향을 사용한다.','공간 곡선이며 시간에 따른 입자 궤도나 에너지 수송 해가 아니다. 적분 종료는 물리적 자기장 경계가 아니다.'),
  item('ε EPSILON · softening · 정규화 · 부동소수점 · 로그 합성','수치','표시·수치 기법','자기원 중심 특이점을 0.05 R_E로 완화한다. 큰 세기는 로그 스케일로 합산하며 벡터 방향과 크기를 분리한다.','완화 반경 내부와 천체 내부는 외부 쌍극자 근사로 실제 장을 재현하지 않는다.'),
  item('Web Worker · FPS · 갱신 Hz · 캐시 · LOD · 버퍼링','수치','표시·수치 기법','자기력선을 별도 작업자에서 계산하고 최대 4 Hz로 최신 형상을 갱신한다. 프레임마다 기존 버퍼를 재사용한다.','FPS는 장치/화면 크기에 따라 다르며 표시 갱신 주파수와 물리 시간 배율은 다르다. 선/샘플 수 예산은 자기장 세기 제한이 아니다.'),
  item('히트맵 heatmap · quiver 벡터장 · composite · stress_only','표시','표시·수치 기법','스칼라 색 지도, 방향 화살표, 복합 렌더, 응력 전용 보기이다. nT 범례가 있는 자기력선은 고정 로그 눈금으로 색을 정한다.','기존 진단 히트맵은 정규화된 비교 점수일 수 있으므로 선택한 지표의 단위를 확인한다.'),
  item('에너지 펄스 · streamlines · 움직이는 점','표시','표시·수치 기법','자기력선의 방향과 연속성을 읽기 위한 애니메이션 점이다.','전자기 에너지 속도·입자 속도·실제 플럭스를 측정한 것이 아니다.'),
  item('gamma γ · opacity · colorPalette · highResGrid · streamlineAlpha','표시','표시·수치 기법','감마는 대비 보정, opacity/alpha는 투명도, palette는 색상, highResGrid는 이미지 샘플 해상도이다.','물리 계산의 증폭이나 검증 정확도 향상과 동일하지 않다.'),
  item('ground sky · 어안 FOV · 방위각 azimuth · 관측 고도 · cloud_density hotspot_mask split_3view','표시','표시·수치 기법','지상 하늘 투영, 시야각, 관측자 위치, 구름/활성 마스크를 분리해 보는 기능이다.','렌즈/투영과 대기 깊이를 단순화한 설명용 보기이며 실제 지상 관측 영상 예측이 아니다.'),
  item('프로브 probe · 우클릭 · 레이어 전체 숨기기 보이기 · fullscreen 줌','표시','표시·수치 기법','선택 위치의 장과 중심 거리를 읽고 개별 표시를 토글한다. 3D 우클릭은 명시된 z=0 단면과 시선의 교점을 측정한다.','3D 화면의 모든 픽셀에 유일한 공간 위치가 존재하는 것은 아니다. 줌과 카메라 회전은 물리량을 바꾸지 않는다.'),
  item('Python 수치 검증 · 대조군 · 차이 Δ · 재현성','검증','표시·수치 기법','현재 입력을 포함한 분석 스크립트를 내보내 같은 조건의 가설/대조군 차이를 확인한다.','코드 테스트 통과는 물리적 가설 입증이 아니다. 극한 입력은 로그 방향 실험이며 일반 수치 내보내기를 중단한다.'),
  item('Gemini API · Worker 프록시 · Turnstile · API key','시스템','표시·수치 기법','외부 AI 설명 서비스, 서버측 API 중계, 봇 방지와 비밀 인증 키를 뜻한다.','AI 답변은 논문 검증을 대체하지 않는다. 키를 소스·브라우저 배포물에 넣지 않는다.'),
  item('가설 검증 · 상관과 인과 · 관측 fact · 귀무가설 · 민감도','검증','기초 이론','관측·근사·가정을 구분하고, 사전 등록한 시공간 기준과 기상 대조군, 독립 자료로 예측력을 비교한다.','보기 좋은 패턴, 수치적 안정성, 매개변수 조정만으로 지진 예측 가설이 입증되지는 않는다.'),
];
